[project]
name = "shantay"
description = "the curiously different batch processor"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache 2.0"}
authors = [{name = "Robert Grimm", email="rgrimm@alum.mit.edu"}]
keywords = ["batch processing", "EU DSA", "statement of reason"]
dynamic = ["version"]

dependencies = [
    "altair", # graphics
    "polars", # data frames
    "pyarrow", # underlying memory representation
    "great_tables", # table formatting
    "ipython", # interactive use
    "ipykernel", # notebooks
]

[project.urls]
repository = "https://github.com/apparebit/shantay"

