name: CI

on:
  push:
    branches: [ "boss" ]
    tags: [ "*" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ vars.DEBUG }}
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    # Pyright is written in JavaScript
    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: "npm"
    - run: npm ci

    - name: Set Up UV incl. Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: 3.12

    - name: Install Dependencies
      run: uv sync

    - name: Run Checks
      run: uv run runtest.py

    - name: Build Wheel
      run: uv build --wheel

    - name: Upload Wheel
      uses: actions/upload-artifact@v4
      with:
        name: shantay
        path: dist

  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set Up UV incl. Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: 3.12

    - name: Create Venv
      run: |
        uv venv
        mkdir dist

    - name: Download Wheel
      uses: actions/download-artifact@v5
      with:
        name: shantay
        path: dist

    - run: echo "WHEEL_NAME=$(find dist/*.whl | tail -n 1 | cut -c 6-)" >> "$GITHUB_ENV"

    - name: Install Wheel
      run: uv pip install "./dist/$WHEEL_NAME"

    - name: Generate Report
      run: |
        python -m shantay visualize
        mkdir reports
        mv dsa-db-staging/builtin.html reports/db.html

    - name: Upload Report
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        name: github-pages
        path: reports/

  deploy:
    needs: [build, report]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
